services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_inventory
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: