// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductInventory.Data;
using ProductInventory.Models;

#nullable disable

namespace ProductInventory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductInventory.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1,
                            Brand = "Brand 1",
                            Category = "Electronics",
                            Name = "Mouse",
                            Price = 6.5,
                            Vendor = "Vendor 1"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1,
                            Brand = "Brand 2",
                            Category = "Electronics",
                            Name = "Keyboard",
                            Price = 9.5,
                            Vendor = "Vendor 2"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1,
                            Brand = "Brand 3",
                            Category = "Electronics",
                            Name = "Screen",
                            Price = 120.59999999999999,
                            Vendor = "Vendor 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
